### ISSUE TITLE
Ruby group capstone - Set up your Kanban board

### ISSUE THREAD

**Issue by Donard97** [codecaiine/catalog-of-my-things#25]
**We created this issue to check if our project was as requested.**

_In this project, we prepared a Kanban board for Ruby's capstone project._

- **This is the link to Ruby capstone project Kanban board:** https://github.com/codecaiine/catalog-of-my-things/projects/1

- **Our team has 4 members:** 

> 1. Team Member 1: @codecaiine 
> 2. Team Member 2: @Donard97 
> 3. Team Member 3: @ahzia 
> 4. Team Team Member 4: @Kossi-stack
> 

 

### Project requirements that are done:

> - Followed steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) and copied template of board ✔️ 
> - Created tasks on Kankab board based on the project requirements ✔️ 

<hr>

_Feel free to review my project and let me know if there are any essential changes 💪 ._

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- Each Card should have the number of points in the `[Xpt]` prefix. That number should indicate the number of `points` that show how complex the task is. **1 point = 1 hour of estimated work**. You shouldn't change the points after dividing up cards, even if the actual work takes longer.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
